name: Angular Modern Build

on:
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build Angular application
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ResidencialOliva

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Verify Angular project
        run: |
          echo "Directorio actual:"
          pwd

          echo "Contenido:"
          ls -la

          test -f angular.json
          test -f package.json
          test -f package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Angular application
        run: npm run build