name: Angular Legacy Build

on:
  push:
    branches: [master, upgrade-angular, legacy-angular-12]
  pull_request:
    branches: [master, upgrade-angular, legacy-angular-12]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2

      - name: Install dependencies
        run: npm install --legacy-peer-deps --ignore-scripts

      - name: Run NGCC
        run: npx ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points

      - name: Build Angular legacy app
        run: npm run build